name: 'phpcs-ci-action'
description: 'PHP code sniffing action to use on PR and pushes'
inputs:
    token:  # id of input
        description: 'Github token'
        required: true
        default: ''
    phpcs-path:
        description: 'Path to PHP codesniffer executable'
        required: true
    phpcs-config:
        description: 'Path to phpcs config ruleset'
        required: true
    php:
        description: 'php version'
        required: true
    exclude-path:
        description: 'path that should be trimmed from filepath in filtering'
        required: true
    filter-script:
        description: 'path to php script to filter sniffer raw output'
        required: true
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
          with:
              fetch-depth: 0
        - run: |
              echo 'Git modified and added php files'
              GIT_MODIFIED_AND_ADDED_PHP_FILES=$(git diff --name-only --diff-filter=AM `git merge-base origin/master HEAD` | grep .php$ || true | xargs)
              echo '-------Git modified PHP files--------'
              echo "$GIT_MODIFIED_AND_ADDED_PHP_FILES"
              echo '-------Git modified PHP files--------'
              echo "::set-output name=git_modified_files::$(echo "$GIT_MODIFIED_AND_ADDED_PHP_FILES")"
              if [ -z "$GIT_MODIFIED_AND_ADDED_PHP_FILES" ]; then
                echo ::set-output name=start_sniffer::0
              else
                echo ::set-output name=start_sniffer::1
              fi
              GIT_CHANGED_FILES_AND_LINES=$(git diff --unified=0 --diff-filter=AM `git merge-base origin/master HEAD` | grep -Po '^\+\+\+ ./\K.*|^@@ -[0-9]+(,[0-9]+)? \+\K[0-9]+(,[0-9]+)?(?= @@)')
              echo "$GIT_CHANGED_FILES_AND_LINES" > git_changed_files_and_lines.txt
              echo '-------Git modified files with lines--------'
              cat git_changed_files_and_lines.txt
              echo '-------Git modified files with lines--------'
          id: git
          env:
              GITHUB_TOKEN: ${{ inputs.token }}
          shell: bash
        - uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ inputs.php }}
              coverage: none
        - run: composer validate
          shell: bash
        - run: |
              composer config --global github-oauth.github.com ${{inputs.token}}
              composer install --no-interaction --no-ansi --prefer-dist --no-suggest --ignore-platform-reqs
          shell: bash
        - run: |
              ${{ inputs.phpcs-path }} --config-set ignore_errors_on_exit 1
              ${{ inputs.phpcs-path }} --config-set ignore_warnings_on_exit 1
              SNIFFER_OUTPUT=$(${{ inputs.phpcs-path }} --standard=${{ inputs.phpcs-config }} --report=csv ${{ steps.git.outputs.git_modified_files }})
              echo '-------Sniffer raw output start--------'
              echo "$SNIFFER_OUTPUT"
              echo "$SNIFFER_OUTPUT" > report.csv
              echo '-------Sniffer raw output finish--------'
              SNIFFER_FILTERED=$(php ${{ inputs.filter-script }} report.csv git_changed_files_and_lines.txt ${{ inputs.exclude-path }})
              echo '-------Sniffer filtered output start--------'
              echo "::add-matcher::.github/phpcs-matcher.json"
              echo "$SNIFFER_FILTERED"
              echo '-------Sniffer filtered output finish--------'
          if: ${{ steps.git.outputs.start_sniffer == 1 }}
          shell: bash
